FROM alpine:3.17.2

RUN apk update
RUN apk add neovim stow
RUN apk add nodejs npm
RUN apk add python3
RUN apk add gcc g++
RUN apk add git
RUN apk add bash

WORKDIR /root
ENV PATH="$PATH:/root/.config/nvim/bin"
