set nobackup
set clipboard=unnamedplus
set cmdheight=1
set conceallevel=0
set fileencoding=utf-8
set hlsearch
set ignorecase
set mouse=a
set noshowmode
set smartcase
set smartindent
set splitbelow
set splitright
set noswapfile
set termguicolors
set timeoutlen=300
set expandtab
set shiftwidth=4
set tabstop=4
set number
set norelativenumber
set numberwidth=4
set nowritebackup
set undofile
set wrap
set linebreak
set viminfofile=NONE
